#!/usr/bin/env bash

cd /home/itjarl1984/working

repositories=(
    git@github.com:ITJarl1984/notes.git
    git@github.com:ITJarl1984/quill-examples-zymposium.git
    git@github.com:ITJarl1984/zio-magic.git
    git@github.com:ITJarl1984/zio-protoquill.git
    git@github.com:ITJarl1984/zio-query.git
    git@github.com:ITJarl1984/zio-quill-gettingstarted.git
    git@github.com:ITJarl1984/zio-quill.git
    git@github.com:ITJarl1984/zio-sql.git
    git@github.com:itjarl1984/build-a-zio-app-from-scratch.git
    git@github.com:itjarl1984/streaming-all-the-way.git
    git@github.com:itjarl1984/zio-config.git
    git@github.com:itjarl1984/zio-logging.git
    git@github.com:itjarl1984/zio-slides.git
    git@github.com:itjarl1984/zio.git
    git@github.com:kitlangton/zio-slides.git
    git@github.com:sheehandustryn/bash-scripts.git
    git@github.com:sheehandustryn/work-notes.git
    git@gitlab.com:/williamhillplc/usa/services/martech/nagaraja/etl-orchestration-service.git
    git@gitlab.com:caesarsdigital/infosec/seceng/us-ddos-accounts-infrastructure/whddos-us-f5-bigip-ltm.git
    git@gitlab.com:caesarsdigital/technical-services/public-cloud/us-landing-zone/http-proxy-whitelist.git
    git@gitlab.com:caesarsdigital/usa/betting-engine/infra/be-helmfile.git
    git@gitlab.com:caesarsdigital/usa/betting-engine/infra/be-kafka-topics-manager.git
    git@gitlab.com:caesarsdigital/usa/betting-engine/infra/charts.git
    git@gitlab.com:caesarsdigital/usa/betting-engine/services/libs/be-sbt-utils.git
    git@gitlab.com:caesarsdigital/usa/betting-engine/services/libs/gatling-kafka.git
    git@gitlab.com:caesarsdigital/usa/betting-engine/services/libs/kafka-contracts/be-accounts-session-topic-lib.git
    git@gitlab.com:caesarsdigital/usa/deployment/sportsbook/firehose.git
    git@gitlab.com:caesarsdigital/usa/deployment/sportsbook/sportsbook-api.git
    git@gitlab.com:caesarsdigital/usa/infrastructure/automation-frameworks/gitlab-ci-job-generator.git
    git@gitlab.com:caesarsdigital/usa/infrastructure/automation-frameworks/gitlab-ci-pipelines.git
    git@gitlab.com:caesarsdigital/usa/infrastructure/helm/charts-individual/base.git
    git@gitlab.com:caesarsdigital/usa/infrastructure/helm/splunk.git
    git@gitlab.com:caesarsdigital/usa/infrastructure/helm/us-platform-config-server-chart.git
    git@gitlab.com:caesarsdigital/usa/infrastructure/helm/whc-k8s-platform/istio.git
    git@gitlab.com:caesarsdigital/usa/infrastructure/kubernetes/platform-helmfile.git
    git@gitlab.com:caesarsdigital/usa/infrastructure/packer/gitlab-runner.git
    git@gitlab.com:caesarsdigital/usa/infrastructure/terraform/aws-msk.git
    git@gitlab.com:caesarsdigital/usa/infrastructure/terraform/aws-new-relic-metric-stream.git
    git@gitlab.com:caesarsdigital/usa/infrastructure/terraform/facebook-conversions-api-gateway.git
    git@gitlab.com:caesarsdigital/usa/infrastructure/terraform/gitlab-runner.git
    git@gitlab.com:caesarsdigital/usa/infrastructure/terraform/new-cloudfront-poc.git
    git@gitlab.com:caesarsdigital/usa/infrastructure/terraform/protected-test-lambda.git
    git@gitlab.com:caesarsdigital/usa/infrastructure/terraform/terragrunt-tf-s3-buckets.git
    git@gitlab.com:caesarsdigital/usa/infrastructure/terraform/tf-cloudfront.git
    git@gitlab.com:caesarsdigital/usa/infrastructure/terraform/tf-f5.git
    git@gitlab.com:caesarsdigital/usa/infrastructure/terraform/tf-new-relic.git
    git@gitlab.com:caesarsdigital/usa/infrastructure/terraform/tf-s3-static-site.git
    git@gitlab.com:caesarsdigital/usa/infrastructure/website-certs/wildcard.us.williamhill.com.git
    git@gitlab.com:caesarsdigital/usa/qa/wdio-liberty-ui-test.git
    git@gitlab.com:caesarsdigital/usa/services/martech/banshee/banshee_core
    git@gitlab.com:caesarsdigital/usa/services/martech/banshee/banshee_helm_chart.git
    git@gitlab.com:caesarsdigital/usa/services/martech/banshee/banshee_kms_terraform.git
    git@gitlab.com:caesarsdigital/usa/services/martech/banshee/banshee_rds_postgres_terraform.git
    git@gitlab.com:caesarsdigital/usa/services/martech/citadel/citadel_kms_terraform.git
    git@gitlab.com:caesarsdigital/usa/services/martech/citadel/citadel_postgres_config_ansible.git
    git@gitlab.com:caesarsdigital/usa/services/martech/citadel/citadel_rds_postgres_terraform.git
    git@gitlab.com:caesarsdigital/usa/services/martech/citadel/citadel_service.git
    git@gitlab.com:caesarsdigital/usa/services/martech/contentstack-backup.git
    git@gitlab.com:caesarsdigital/usa/services/martech/corp-web-us-zero-cool.git
    git@gitlab.com:caesarsdigital/usa/services/martech/dataraiders-cicd-docker-image.git
    git@gitlab.com:caesarsdigital/usa/services/martech/devops-tools/get-nonprod-k8s-def-files.git
    git@gitlab.com:caesarsdigital/usa/services/martech/devops-tools/kafka-tools-ec2.git
    git@gitlab.com:caesarsdigital/usa/services/martech/devops-tools/local-corp-web-us-zero-cool-helm-template.git
    git@gitlab.com:caesarsdigital/usa/services/martech/devops-tools/local-firehose-helm-template.git
    git@gitlab.com:caesarsdigital/usa/services/martech/devops-tools/local-looker-action-hub-helm-template.git
    git@gitlab.com:caesarsdigital/usa/services/martech/devops-tools/update-repo-trunk-branches.git
    git@gitlab.com:caesarsdigital/usa/services/martech/experimental/bigquery-etl.git
    git@gitlab.com:caesarsdigital/usa/services/martech/experimental/firehose_service
    git@gitlab.com:caesarsdigital/usa/services/martech/experimental/scala-executor-ec2.git
    git@gitlab.com:caesarsdigital/usa/services/martech/firehose/firehose_service.git
    git@gitlab.com:caesarsdigital/usa/services/martech/helm_charts/analytics-postgresql.git
    git@gitlab.com:caesarsdigital/usa/services/martech/helm_charts/analytics_bigquery_ga_etl.git
    git@gitlab.com:caesarsdigital/usa/services/martech/helm_charts/analytics_citadel.git
    git@gitlab.com:caesarsdigital/usa/services/martech/helm_charts/analytics_firehose.git
    git@gitlab.com:caesarsdigital/usa/services/martech/helm_charts/analytics_looker_action_hub.git
    git@gitlab.com:caesarsdigital/usa/services/martech/helm_charts/analytics_marketo_etl.git
    git@gitlab.com:caesarsdigital/usa/services/martech/helm_charts/analytics_vorax.git
    git@gitlab.com:caesarsdigital/usa/services/martech/helm_charts/analytics_xorn.git
    git@gitlab.com:caesarsdigital/usa/services/martech/helm_charts/conversions-zero-cool.git
    git@gitlab.com:caesarsdigital/usa/services/martech/helm_charts/martech_base_chart.git
    git@gitlab.com:caesarsdigital/usa/services/martech/k6/k6-service.git
    git@gitlab.com:caesarsdigital/usa/services/martech/looker_action_hub/analytics_looker_action_hub_cloudfront_terraform.git
    git@gitlab.com:caesarsdigital/usa/services/martech/looker_action_hub/analytics_looker_action_hub_service.git
    git@gitlab.com:caesarsdigital/usa/services/martech/mars/mars_core.git
    git@gitlab.com:caesarsdigital/usa/services/martech/mars/mars_kms_terraform.git
    git@gitlab.com:caesarsdigital/usa/services/martech/mars/mars_rds_postgres_terraform.git
    git@gitlab.com:caesarsdigital/usa/services/martech/martech-analytics-postgresql-cluster.git
    git@gitlab.com:caesarsdigital/usa/services/martech/martech_docker_images/helm-tools.git
    git@gitlab.com:caesarsdigital/usa/services/martech/martech_docker_images/martech_gatling_runner.git
    git@gitlab.com:caesarsdigital/usa/services/martech/martech_docker_images/utility_tools.git
    git@gitlab.com:caesarsdigital/usa/services/martech/martech_s3_storage.git
    git@gitlab.com:caesarsdigital/usa/services/martech/models/backend-models.git
    git@gitlab.com:caesarsdigital/usa/services/martech/nagaraja/bigquery-ga-etl.git
    git@gitlab.com:caesarsdigital/usa/services/martech/nagaraja/marketo-etl.git
    git@gitlab.com:caesarsdigital/usa/services/martech/optimizely/optimizely-agent-chart.git
    git@gitlab.com:caesarsdigital/usa/services/martech/optimizely/optimizely-service.git
    git@gitlab.com:caesarsdigital/usa/services/martech/spark-infrastructure.git
    git@gitlab.com:caesarsdigital/usa/services/martech/terraform/martech-snowflake.git
    git@gitlab.com:caesarsdigital/usa/services/martech/terraform_modules/s3_for_snowflake.git
    git@gitlab.com:caesarsdigital/usa/services/martech/vorax/vorax_service.git
    git@gitlab.com:caesarsdigital/usa/services/martech/vorax_gatling/analytics_vorax_gatling_chart.git
    git@gitlab.com:caesarsdigital/usa/services/martech/vorax_gatling/analytics_vorax_gatling_core.git
    git@gitlab.com:caesarsdigital/usa/services/martech/vorax_gatling/analytics_vorax_gatling_terraform.git
    git@gitlab.com:caesarsdigital/usa/services/martech/wdio/wdio_service.git
    git@gitlab.com:caesarsdigital/usa/services/martech/xorn/xorn_service.git
    git@gitlab.com:caesarsdigital/usa/services/smart-data-platform/ci-docker-image.git
    git@gitlab.com:caesarsdigital/usa/services/smart-data-platform/helm.astronomer.io
    git@gitlab.com:caesarsdigital/usa/services/smart-data-platform/sdp-docker-images.git
    git@gitlab.com:caesarsdigital/usa/services/smart-data-platform/smart-data-platform-astronomer/airflow-chart
    git@gitlab.com:caesarsdigital/usa/services/smart-data-platform/smart-data-platform-astronomer/astronomer
    git@gitlab.com:caesarsdigital/usa/services/smart-data-platform/smart-data-platform-commons.git
    git@gitlab.com:caesarsdigital/usa/services/smart-data-platform/smart-data-platform-helms.git
    git@gitlab.com:caesarsdigital/usa/services/smart-data-platform/smart-data-platform-martech.git
    git@gitlab.com:caesarsdigital/usa/services/smart-data-platform/smart-data-platform-scripts.git
    git@gitlab.com:caesarsdigital/usa/services/smart-data-platform/smart-data-platform-terraform-modules/aws-eks
    git@gitlab.com:caesarsdigital/usa/services/smart-data-platform/smart-data-platform-terraform-modules/gitlab-runner
    git@gitlab.com:caesarsdigital/usa/services/smart-data-platform/smart-data-platform-terraform-modules/helm.astronomer.io
    git@gitlab.com:caesarsdigital/usa/services/smart-data-platform/smart-data-platform-terraform-modules/landing-zone-bucket
    git@gitlab.com:caesarsdigital/usa/services/smart-data-platform/smart-data-platform-terraform-modules/powerbi-data-gateway
    git@gitlab.com:caesarsdigital/usa/services/smart-data-platform/smart-data-platform-terraform-modules/private-link
    git@gitlab.com:caesarsdigital/usa/services/smart-data-platform/smart-data-platform-terraform-modules/secrets-manager
    git@gitlab.com:caesarsdigital/usa/services/smart-data-platform/smart-data-platform-us-access-management
    git@gitlab.com:caesarsdigital/usa/services/smart-data-platform/smart-data-platform-us-logical
    git@gitlab.com:caesarsdigital/usa/services/smart-data-platform/smart-data-platform-us-physical
    git@gitlab.com:caesarsdigital/usa/services/smart-data-platform/us-global-platform
    git@gitlab.com:caesarsdigital/usa/services/sportsbook/compliance-reconcilliation.git
    git@gitlab.com:caesarsdigital/usa/services/sportsbook/corp-web-us
    git@gitlab.com:caesarsdigital/usa/services/sportsbook/data-raiders.git
    git@gitlab.com:caesarsdigital/usa/services/sportsbook/metadata-cicd-image.git
    git@gitlab.com:caesarsdigital/usa/services/sportsbook/pam-api-gateway.git
    git@gitlab.com:caesarsdigital/usa/services/sportsbook/sportsbook-api-nj
    git@gitlab.com:caesarsdigital/usa/services/sportsbook/us-platform-config-server.git
    git@gitlab.com:caesarsdigital/usa/shared/helm/sportsbook-charts.git
    git@gitlab.com:caesarsdigital/usa/shared/scripts/devops-environment.git
    git@gitlab.com:caesarsdigital/usa/shared/scripts/nj-mac-mini-housekeeper.git
    git@gitlab.com:caesarsdigital/usa/shared/terraform/ns1.git
    git@gitlab.com:williamhillplc/infosec/seceng/us-ddos-accounts-infrastructure/whddos-us-f5-bigip-ltm.git
    git@gitlab.com:williamhillplc/technical-services/public-cloud/us-landing-zone/http-proxy-whitelist.git
    git@gitlab.com:williamhillplc/usa/betting-engine/infra/be-helmfile.git
    git@gitlab.com:williamhillplc/usa/betting-engine/infra/be-kafka-topics-manager.git
    git@gitlab.com:williamhillplc/usa/betting-engine/infra/charts.git
    git@gitlab.com:williamhillplc/usa/betting-engine/services/libs/be-sbt-utils.git
    git@gitlab.com:williamhillplc/usa/betting-engine/services/libs/gatling-kafka.git
    git@gitlab.com:williamhillplc/usa/betting-engine/services/libs/kafka-contracts/be-accounts-session-topic-lib.git
    git@gitlab.com:williamhillplc/usa/deployment/sportsbook/firehose.git
    git@gitlab.com:williamhillplc/usa/deployment/sportsbook/sportsbook-api.git
    git@gitlab.com:williamhillplc/usa/infrastructure/automation-frameworks/gitlab-ci-job-generator.git
    git@gitlab.com:williamhillplc/usa/infrastructure/automation-frameworks/gitlab-ci-pipelines.git
    git@gitlab.com:williamhillplc/usa/infrastructure/helm/charts-individual/base.git
    git@gitlab.com:williamhillplc/usa/infrastructure/helm/splunk.git
    git@gitlab.com:williamhillplc/usa/infrastructure/helm/us-platform-config-server-chart.git
    git@gitlab.com:williamhillplc/usa/infrastructure/helm/whc-k8s-platform/istio.git
    git@gitlab.com:williamhillplc/usa/infrastructure/kubernetes/platform-helmfile.git
    git@gitlab.com:williamhillplc/usa/infrastructure/packer/gitlab-runner.git
    git@gitlab.com:williamhillplc/usa/infrastructure/terraform/aws-msk.git
    git@gitlab.com:williamhillplc/usa/infrastructure/terraform/aws-new-relic-metric-stream.git
    git@gitlab.com:williamhillplc/usa/infrastructure/terraform/facebook-conversions-api-gateway.git
    git@gitlab.com:williamhillplc/usa/infrastructure/terraform/gitlab-runner.git
    git@gitlab.com:williamhillplc/usa/infrastructure/terraform/new-cloudfront-poc.git
    git@gitlab.com:williamhillplc/usa/infrastructure/terraform/protected-test-lambda.git
    git@gitlab.com:williamhillplc/usa/infrastructure/terraform/terragrunt-tf-s3-buckets.git
    git@gitlab.com:williamhillplc/usa/infrastructure/terraform/tf-cloudfront.git
    git@gitlab.com:williamhillplc/usa/infrastructure/terraform/tf-f5.git
    git@gitlab.com:williamhillplc/usa/infrastructure/terraform/tf-new-relic.git
    git@gitlab.com:williamhillplc/usa/infrastructure/terraform/tf-s3-static-site.git
    git@gitlab.com:williamhillplc/usa/qa/wdio-liberty-ui-test.git
    git@gitlab.com:williamhillplc/usa/services/martech/banshee/banshee_core.git
    git@gitlab.com:williamhillplc/usa/services/martech/banshee/banshee_helm_chart.git
    git@gitlab.com:williamhillplc/usa/services/martech/banshee/banshee_kms_terraform.git
    git@gitlab.com:williamhillplc/usa/services/martech/banshee/banshee_rds_postgres_terraform.git
    git@gitlab.com:williamhillplc/usa/services/martech/citadel/citadel_kms_terraform.git
    git@gitlab.com:williamhillplc/usa/services/martech/citadel/citadel_postgres_config_ansible.git
    git@gitlab.com:williamhillplc/usa/services/martech/citadel/citadel_rds_postgres_terraform.git
    git@gitlab.com:williamhillplc/usa/services/martech/citadel/citadel_service.git
    git@gitlab.com:williamhillplc/usa/services/martech/contentstack-backup.git
    git@gitlab.com:williamhillplc/usa/services/martech/corp-web-us-zero-cool.git
    git@gitlab.com:williamhillplc/usa/services/martech/dataraiders-cicd-docker-image.git
    git@gitlab.com:williamhillplc/usa/services/martech/devops-tools/get-nonprod-k8s-def-files.git
    git@gitlab.com:williamhillplc/usa/services/martech/devops-tools/kafka-tools-ec2.git
    git@gitlab.com:williamhillplc/usa/services/martech/devops-tools/local-corp-web-us-zero-cool-helm-template.git
    git@gitlab.com:williamhillplc/usa/services/martech/devops-tools/local-firehose-helm-template.git
    git@gitlab.com:williamhillplc/usa/services/martech/devops-tools/local-looker-action-hub-helm-template.git
    git@gitlab.com:williamhillplc/usa/services/martech/devops-tools/macos-dotfiles.git
    git@gitlab.com:williamhillplc/usa/services/martech/devops-tools/update-repo-trunk-branches.git
    git@gitlab.com:williamhillplc/usa/services/martech/experimental/bigquery-etl.git
    git@gitlab.com:williamhillplc/usa/services/martech/experimental/firehose_service
    git@gitlab.com:williamhillplc/usa/services/martech/experimental/scala-executor-ec2.git
    git@gitlab.com:williamhillplc/usa/services/martech/firehose/firehose_service.git
    git@gitlab.com:williamhillplc/usa/services/martech/helm_charts/analytics-postgresql.git
    git@gitlab.com:williamhillplc/usa/services/martech/helm_charts/analytics_bigquery_ga_etl.git
    git@gitlab.com:williamhillplc/usa/services/martech/helm_charts/analytics_citadel.git
    git@gitlab.com:williamhillplc/usa/services/martech/helm_charts/analytics_firehose.git
    git@gitlab.com:williamhillplc/usa/services/martech/helm_charts/analytics_looker_action_hub.git
    git@gitlab.com:williamhillplc/usa/services/martech/helm_charts/analytics_marketo_etl.git
    git@gitlab.com:williamhillplc/usa/services/martech/helm_charts/analytics_vorax.git
    git@gitlab.com:williamhillplc/usa/services/martech/helm_charts/analytics_xorn.git
    git@gitlab.com:williamhillplc/usa/services/martech/helm_charts/conversions-zero-cool.git
    git@gitlab.com:williamhillplc/usa/services/martech/helm_charts/martech_base_chart.git
    git@gitlab.com:williamhillplc/usa/services/martech/k6/k6-service.git
    git@gitlab.com:williamhillplc/usa/services/martech/looker_action_hub/analytics_looker_action_hub_cloudfront_terraform.git
    git@gitlab.com:williamhillplc/usa/services/martech/looker_action_hub/analytics_looker_action_hub_service.git
    git@gitlab.com:williamhillplc/usa/services/martech/mars/mars_core.git
    git@gitlab.com:williamhillplc/usa/services/martech/mars/mars_kms_terraform.git
    git@gitlab.com:williamhillplc/usa/services/martech/mars/mars_rds_postgres_terraform.git
    git@gitlab.com:williamhillplc/usa/services/martech/martech-analytics-postgresql-cluster.git
    git@gitlab.com:williamhillplc/usa/services/martech/martech_docker_images/martech_gatling_runner.git
    git@gitlab.com:williamhillplc/usa/services/martech/martech_docker_images/utility_tools.git
    git@gitlab.com:williamhillplc/usa/services/martech/martech_s3_storage.git
    git@gitlab.com:williamhillplc/usa/services/martech/models/backend-models.git
    git@gitlab.com:williamhillplc/usa/services/martech/nagaraja/bigquery-ga-etl.git
    git@gitlab.com:williamhillplc/usa/services/martech/nagaraja/marketo-etl.git
    git@gitlab.com:williamhillplc/usa/services/martech/spark-infrastructure.git
    git@gitlab.com:williamhillplc/usa/services/martech/terraform/martech-snowflake.git
    git@gitlab.com:williamhillplc/usa/services/martech/terraform_modules/s3_for_snowflake.git
    git@gitlab.com:williamhillplc/usa/services/martech/vorax/vorax_service.git
    git@gitlab.com:williamhillplc/usa/services/martech/vorax_gatling/analytics_vorax_gatling_chart.git
    git@gitlab.com:williamhillplc/usa/services/martech/vorax_gatling/analytics_vorax_gatling_core.git
    git@gitlab.com:williamhillplc/usa/services/martech/vorax_gatling/analytics_vorax_gatling_terraform.git
    git@gitlab.com:williamhillplc/usa/services/martech/wdio/wdio_service.git
    git@gitlab.com:williamhillplc/usa/services/martech/xorn/xorn_service.git
    git@gitlab.com:williamhillplc/usa/services/smart-data-platform/ci-docker-image.git
    git@gitlab.com:williamhillplc/usa/services/smart-data-platform/helm.astronomer.io
    git@gitlab.com:williamhillplc/usa/services/smart-data-platform/sdp-docker-images.git
    git@gitlab.com:williamhillplc/usa/services/smart-data-platform/smart-data-platform-astronomer/airflow-chart
    git@gitlab.com:williamhillplc/usa/services/smart-data-platform/smart-data-platform-astronomer/astronomer
    git@gitlab.com:williamhillplc/usa/services/smart-data-platform/smart-data-platform-commons.git
    git@gitlab.com:williamhillplc/usa/services/smart-data-platform/smart-data-platform-helms.git
    git@gitlab.com:williamhillplc/usa/services/smart-data-platform/smart-data-platform-martech.git
    git@gitlab.com:williamhillplc/usa/services/smart-data-platform/smart-data-platform-scripts.git
    git@gitlab.com:williamhillplc/usa/services/smart-data-platform/smart-data-platform-terraform-modules/aws-eks
    git@gitlab.com:williamhillplc/usa/services/smart-data-platform/smart-data-platform-terraform-modules/gitlab-runner
    git@gitlab.com:williamhillplc/usa/services/smart-data-platform/smart-data-platform-terraform-modules/helm.astronomer.io
    git@gitlab.com:williamhillplc/usa/services/smart-data-platform/smart-data-platform-terraform-modules/landing-zone-bucket
    git@gitlab.com:williamhillplc/usa/services/smart-data-platform/smart-data-platform-terraform-modules/powerbi-data-gateway
    git@gitlab.com:williamhillplc/usa/services/smart-data-platform/smart-data-platform-terraform-modules/private-link
    git@gitlab.com:williamhillplc/usa/services/smart-data-platform/smart-data-platform-terraform-modules/secrets-manager
    git@gitlab.com:williamhillplc/usa/services/smart-data-platform/smart-data-platform-us-access-management
    git@gitlab.com:williamhillplc/usa/services/smart-data-platform/smart-data-platform-us-logical
    git@gitlab.com:williamhillplc/usa/services/smart-data-platform/smart-data-platform-us-physical
    git@gitlab.com:williamhillplc/usa/services/smart-data-platform/us-global-platform
    git@gitlab.com:williamhillplc/usa/services/sportsbook/compliance-reconcilliation.git
    git@gitlab.com:williamhillplc/usa/services/sportsbook/corp-web-us
    git@gitlab.com:williamhillplc/usa/services/sportsbook/data-raiders.git
    git@gitlab.com:williamhillplc/usa/services/sportsbook/metadata-cicd-image.git
    git@gitlab.com:williamhillplc/usa/services/sportsbook/pam-api-gateway.git
    git@gitlab.com:williamhillplc/usa/services/sportsbook/sportsbook-api-nj
    git@gitlab.com:williamhillplc/usa/services/sportsbook/us-platform-config-server.git
    git@gitlab.com:williamhillplc/usa/shared/helm/sportsbook-charts.git
    git@gitlab.com:williamhillplc/usa/shared/scripts/devops-environment.git
    git@gitlab.com:williamhillplc/usa/shared/scripts/nj-mac-mini-housekeeper.git
    git@gitlab.com:williamhillplc/usa/shared/terraform/ns1.git
    https://github.com/Antiarchitect/asdf-helm.git
    https://github.com/Banno/asdf-hashicorp.git
    https://github.com/GoogleCloudDataproc/spark-bigquery-connector.git
    https://github.com/GoogleContainerTools/kaniko.git
    https://github.com/MetricMike/asdf-awscli.git
    https://github.com/VundleVim/Vundle.vim.git
    https://github.com/agkozak/zsh-z
    https://github.com/asdf-community/asdf-ocaml.git
    https://github.com/asdf-community/asdf-opam.git
    https://github.com/asdf-vm/asdf-plugins.git
    https://github.com/asdf-vm/asdf.git
    https://github.com/bhilburn/powerlevel9k.git
    https://github.com/databus23/helm-diff
    https://github.com/elementalvoid/asdf-saml2aws.git
    https://github.com/feniix/asdf-sops.git
    https://github.com/hashicorp/learn-terraform-count-foreach.git
    https://github.com/jldeen/dotfiles.git
    https://github.com/nvm-sh/nvm.git
    https://github.com/ohmer/asdf-terragrunt.git
    https://github.com/ohmyzsh/ohmyzsh.git
    https://github.com/optimizely/agent.git
    https://github.com/rbenv/rbenv.git
    https://github.com/rbenv/ruby-build.git
    https://github.com/romkatv/powerlevel10k.git
    https://github.com/scala/scala3-example-project.git
    https://github.com/scrooloose/nerdtree.git
    https://github.com/sheerun/vim-wombat-scheme.git
    https://github.com/tmux-plugins/tpm
    https://github.com/zsh-users/zsh-autosuggestions
    https://github.com/zsh-users/zsh-completions
    https://github.com/zsh-users/zsh-syntax-highlighting.git
)

for repository in ${repositories[@]}
do
    if [[ $repository =~ .*github* ]]
    then
        path=$(echo $repository | sed 's/https:\/\/github.com\///; s/git@github.com://; s/\.git//')
        mkdir --parents --verbose "/home/itjarl1984/working/github/${path}"
        cd "/home/itjarl1984/working/github/${path}" && cd ..
        git clone $repository
    elif [[ $repository =~ .*gitlab* ]]
    then
        path=$(echo $repository | sed 's/git@gitlab.com://; s/\.git//')
        mkdir --parents --verbose "/home/itjarl1984/working/gitlab/${path}"
        cd "/home/itjarl1984/working/gitlab/${path}" && cd ..
        git clone $repository
    else
        continue    
    fi
done

